import {ReactNode} from "react";
import type {Metadata} from "next";
import localFont from "next/font/local";
import {Inter as FontSans} from 'next/font/google';
import ThemeProvider from "@/components/ui/ThemeProvider";

import "./globals.css";



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});


const fontSans = FontSans({
  subsets: ['latin'],
  variable: "--font-sans",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en"  suppressContentEditableWarning>
      <body
        className={`${fontSans.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
      >
        {children}
      </ThemeProvider>

      </body>
    </html>
  );
}
